apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: keda-app:1.0
        imagePullPolicy: Never
        command: ["python"]
        args: ["consumer.py"]
        env:
        - name: BOOTSTRAP_SERVER
          value: "192.168.31.125:9092"
        - name: TOPIC_NAME
          value: "keda-test"
        - name: WAIT_TIME
          value: "2"
        
